application: calc-bot
version: dev1.1
runtime: go
api_version: go1

threadsafe: yes

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "60s"
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "99s"

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  expiration: "1h"

- url: /img
  static_dir: static/img
  expiration: "10s"
  secure: always

- url: /demo
  static_dir: static/demo
  expiration: "10s"
  secure: always

- url: /5F4BAA801B97B9A93D1F038177783A83.txt
  static_files: 5F4BAA801B97B9A93D1F038177783A83.txt
  upload: 5F4BAA801B97B9A93D1F038177783A83.txt
  expiration: "1m"

- url: /(api|bot/(fbm|telegram|skype|kik|line|wechat)|cron|taskqueu)/.*
  script: _go_app
